// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Plano.Models
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // CurrencyProps
    public class CurrencyProp
    {
        public long Cpid { get; set; } // CPID (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string Symbol { get; set; } // Symbol (length: 5)
        public string CurrencyCode { get; set; } // CurrencyCode (length: 5)
        public short? DecimalPlace { get; set; } // DecimalPlace
    }

}
// </auto-generated>
