// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Plano.Models
{
    // ExchangeRates
    public class ExchangeRate
    {
        public long Erid { get; set; } // ERID (Primary key)
        public string CurrencyCode { get; set; } // CurrencyCode (length: 50)
        public decimal? ExchangeRates { get; set; } // ExchangeRates
        public bool? IsDefault { get; set; } // IsDefault
    }

}
// </auto-generated>
