// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Plano.Models
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // CurrencyProps
    public class CurrencyPropConfiguration : IEntityTypeConfiguration<CurrencyProp>
    {
        public void Configure(EntityTypeBuilder<CurrencyProp> builder)
        {
            builder.ToTable("CurrencyProps", "dbo");
            builder.HasKey(x => x.Cpid).HasName("PK_CurrencyProps").IsClustered();

            builder.Property(x => x.Cpid).HasColumnName(@"CPID").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Symbol).HasColumnName(@"Symbol").HasColumnType("nvarchar(5)").IsRequired(false).HasMaxLength(5);
            builder.Property(x => x.CurrencyCode).HasColumnName(@"CurrencyCode").HasColumnType("nvarchar(5)").IsRequired(false).HasMaxLength(5);
            builder.Property(x => x.DecimalPlace).HasColumnName(@"DecimalPlace").HasColumnType("smallint").IsRequired(false);
        }
    }

}
// </auto-generated>
