// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;

namespace Plano.Models
{
    public class PlanoDbContextFactory : IDesignTimeDbContextFactory<PlanoDbContext>
    {
        public PlanoDbContext CreateDbContext(string[] args)
        {
            return new PlanoDbContext();
        }
    }
}
// </auto-generated>
